# Generated by Django 2.2.6 on 2020-03-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketapi',
            name='data',
            field=models.TextField(max_length=1000),
        ),
    ]
